### ISSUE TITLE
A table for active forks

### ISSUE THREAD

**Issue by yairchu** [sudara/awesome-juce#1]
The JUCE ARA fork exists on the "Frameworks" list, but it's just a JUCE fork that adds ARA plugins support.

Once such a table exist I would like to open another issue to add https://github.com/soundradix/JUCE, which is a JUCE fork with several bug-fixes and added features (for example AAX AudioSuite support)

**Comment by sudara** [comment]
Good idea to have a "Forks" category. Any others that you are aware of?

**Comment by yairchu** [comment]
> Good idea to have a "Forks" category. Any others that you are aware of?

None that I'm aware of

**Comment by sudara** [comment]
Added in 01eb116abddd48e5dd747819f1dc2d9f5fc96f78 — thanks for the idea!
