### ISSUE TITLE
[SUGGESTION] badges for (almost) realtime updates

### ISSUE THREAD

**Issue by forart** [sudara/awesome-juce#30]
Hi there, thanks for your (volunteer) work, the collection is very nice and useful !

Since we manage a similar one ([HyMPS](https://github.com/forart/HyMPS#readme), check it out), we suggest you adopt graphic symbols (we use badges) for licenses/stars/updates columns in order to make the list more easily consultable "at a glance".

Here's an example for your first row:
| repo | description | license | ⭐️ | updated |
| :--- | :--- | :---: | :---: | ---: |
|[Gin](https://github.com/FigBug/Gin) <br/> <sup>by [FigBug](https://github.com/FigBug)</sup> | Massive collection of extras, including StackBlur, Websockets, Maps, etc|[![](https://flat.badgen.net/github/license/FigBug/Gin?label=)](https://github.com/FigBug/Gin/blob/master/LICENSE)|[![](https://flat.badgen.net/github/stars/FigBug/Gin?label=)](https://github.com/FigBug/Gin/forks)|[![](https://flat.badgen.net/github/last-commit/FigBug/Gin?label=)](https://github.com/FigBug/Gin/graphs/code-frequency)|

(note: of course, you need to customize badges aspect, links etc.)

Last but not least: do you think your update script is adaptable for our list too ?

Hope that inspires !

**Comment by sudara** [comment]
Howdy!

Your lists are cool, nice work!

Yes, you'd be able to adapt the script, you'd just need to have txt files that follow the rules (the way the categories are listed, one line per github repo, etc)

I'm not sure I find the labels with color / different font sizes more scannable than just text — but thanks for the suggestion! 

Your comment me realize we accidentally switched to the full license description from the short hand, so i'll get that fixed up.

Thanks!
