### ISSUE TITLE
Some projects to Add.

### ISSUE THREAD

**Issue by KottV** [sudara/awesome-juce#4]
Hi!

I think the Cabbage (JUCE/CSound Framework) must be here:
https://github.com/rorywalsh/cabbage https://github.com/rorywalsh/cabbage

and PlugData (JUCE/PureData):
https://github.com/timothyschoen/PlugData/

Couple of nice modules:
https://github.com/nberr/juce-modules
https://suzuki-kengo.dev/

**Comment by sudara** [comment]
Thanks for the heads up on cabbage and plugdata! 

Is the nberr repo just a ADSR module?

Kengo's projects should already all be listed.

**Comment by KottV** [comment]
https://github.com/Archie3d/aeolus_plugin Pipe organ emulator (JUCEd http://kokkinizita.linuxaudio.org/linuxaudio/aeolus/index.html)
https://github.com/apohl79/audiogridder Client-Server plugin bridge
https://github.com/helio-fm cool sequencer (https://helio.fm/)
https://github.com/christofmuc/JammerNetz Jamming over the net
https://github.com/Birch-san/juicysfplugin SounFont player
https://github.com/christofmuc/KnobKraft-orm MIDI Sysex Librarian
https://librearp.gitlab.io/ Arpeggiator
https://github.com/yokemura/Magical8bitPlug2 8bit/Chiptune synth

Roland Rabien stuff (not just Gin):
https://github.com/FigBug/slPlugins https://github.com/FigBug/SN76489 https://github.com/FigBug/SID https://github.com/FigBug/PAPU https://github.com/FigBug/mverb https://github.com/FigBug/Voc https://github.com/FigBug/RP2A03

**Comment by sudara** [comment]
I think I got all these! Thanks again for the help!
